services:
  front:
    container_name: jwt_sign_front
    build: frontend
    user: node
    # stdin_open: true 
    # tty: true
    ports:
      - ${NEXT_PORT}:3000
    restart: on-failure
    depends_on:
      - api
    # volumes:
    #   - ./frontend/:/home/node/app
    working_dir: /home/node/app
  api:
    container_name: jwt_sign_api
    build: backend
    user: node
    # stdin_open: true 
    # tty: true
    ports:
      - 3001:3001
    restart: on-failure
    depends_on:
      - db
    # volumes:
    #   - ./backend/:/home/app
    working_dir: /home/node/app
    environment:
      - API_PORT=3001
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
  db:
    container_name: jwt_sign_db
    image: mysql:8.0.33
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: on-failure
